config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'articles/index'
  root to: "articles#index"
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  # テーブル感のアソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy
  # // テーブル感のアソシエーション

  # active hashのアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  # // active hashのアソシエーション
  
  with_options presence: true do
    validates :title
    validates :genre_id
    validates :text
  end

  with_options numericality: { other_than: 0 } do
    validates :genre_id
  end
end

app/models/classroom.rb
class Classroom < ActiveHash::Base
  self.data = [
    { id: 0, classroom_id: '--' },
    { id: 1, classroom_id: '渋谷アジアビル校' },
    { id: 2, classroom_id: '東京大手町校' },
    { id: 3, classroom_id: '名古屋栄校' },
    { id: 4, classroom_id: 'なんばスカイオ校' },
    { id: 5, classroom_id: '渋谷フォンティスビル校' },
    { id: 6, classroom_id: '渋谷フレーム神南坂校' },
    { id: 7, classroom_id: '東京丸の内校' },
    { id: 8, classroom_id: '近鉄難波ビル校' },
    { id: 9, classroom_id: '中洲校' },
    { id: 10, classroom_id: '天神校' },
    { id: 11, classroom_id: 'オンライン' }
  ]

  include ActiveHash::Associations
  has_many :users
  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  with_options presence: true do
    validates :text
  end
end

app/models/course_style.rb
class CourseStyle < ActiveHash::Base
  self.data = [
    { id: 0, course_style_id: '--' },
    { id: 1, course_style_id: '短期集中スタイル' },
    { id: 2, course_style_id: '夜間休日スタイル' }
  ]

  include ActiveHash::Associations
  has_many :users
  end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 0, genre_id: '--' },
    { id: 1, genre_id: '悩み' },
    { id: 2, genre_id: 'エラー' },
    { id: 3, genre_id: '技術内容' },
    { id: 4, genre_id: '恋愛' },
    { id: 5, genre_id: '人間関係' },
    { id: 6, genre_id: 'キャリア' },
    { id: 7, genre_id: '家庭' },
    { id: 8, genre_id: '体調' },
    { id: 9, genre_id: '自己実現' },
    { id: 10, genre_id: 'その他' }
  ]
 
   include ActiveHash::Associations
   has_many :articles
 
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # テーブル間のアソシエーション
  has_many :articles
  has_many :comments
  # // テーブル間のアソシエーション

  # active hashのアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :classroom
  belongs_to :course_style
  # // active hashのアソシエーション

  with_options presence: true do
    validates :email
    validates :password
    validates :nickname
    validates :time_to_attend
    validates :classroom_id
    validates :course_style_id
  end

  with_options numericality: { other_than: 0 } do
    validates :classroom_id
    validates :course_style_id
  end

  with_options format: { with: /\A[a-zA-Z0-9]+\z/ } do
    validates :password
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :time_to_attend, :classroom_id, :course_style_id])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update]
  before_action :authenticate_user!, only: [:new, :edit,:destroy]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @articles = Article.includes(:user)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.includes(:user)
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    article = Article.find(params[:id])
    if article.destroy
      redirect_to root_path
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :genre_id, :text).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @article.user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to article_path(@comment.article)
    else
      @article = @comment.article
      @comments = @article.comments
      render "article/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, article_id: params[:article_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="card">
  <div class="card__body">
    <%= link_to article.title, article_path(article.id), class: :card__title%>
    <p class="card__summary">
      <%= article.text %>
    </p>
    <%= link_to "by #{article.user.nickname}", user_path(article.user), class: :card__user %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with model: article, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :genre_id, "ジャンル" %><br />
    <%# <%= f.text_area :genre_id, class: :form__text, id:"prototype_catch_copy" %>
    <%= f.collection_select(:genre_id, Genre.all, :id, :genre_id, {} ) %>
  </div>

  <div class="field">
    <%= f.label :text, "記事" %><br />
    <%= f.text_area :text, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">記事編集</h2>
      <%= render partial: "form", locals: { article: @article } %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは
        <%= link_to "#{current_user.nickname}", user_path(current_user), class: :greeting__link%>
        さんがログインしています
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'article', collection: @articles %>
    </div>
  </div>
</main>

app/views/articles/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規記事投稿</h2>
        <%= render partial: "form", locals: { article: @article } %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @article.title %>
      </p>
      <%= link_to "by #{@article.user.nickname}", user_path(@article.user), class: :prototype__user %>
      <% if current_user == @article.user  %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_article_path(@article.id), class: :prototype__btn %>
          <%= link_to "削除する", article_path(@article.id), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
     
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">ジャンル</p>
          <p class="detail__message">
            <%= @article.genre.genre_id %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">投稿文</p>
          <p class="detail__message">
            <%= @article.text %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [@article, @comment], local: true) do |f| %>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.text %>
              <%= link_to "（#{comment.user.nickname}）", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>techcamp-community</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("brand-logo-fill-9b53d90efe0741175ef443b92b47cd44.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "記事投稿", new_article_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @user.nickname %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">ニックネーム</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col1">受講期</th>
            <td class="table__col2"><%= @user.time_to_attend %></td>
          </tr>
          <tr>
            <th class="table__col1">教室</th>
            <td class="table__col2"><%= @user.classroom.classroom_id %></td>
          </tr>
          <tr>
            <th class="table__col1">受講スタイル</th>
            <td class="table__col2"><%= @user.course_style.course_style_id %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんのプロトタイプ"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'articles/article', collection: @user.articles %>
      </div>
    </div>
  </div>
</div>